name: Mongodb CI CD Example

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

defaults:
  run:
    working-directory: ./mongodb

jobs:
  container-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm test
      - run: node client.js
